meta_product_name: "helpal"
meta_title: "helpal - Get help anywhere anytime!"
meta_description: "helpal helps you find help when you need it most. At helpal, we believe in connecting people with diverse skills and backgrounds to work together at solving a variety of tasks that might seem daunting to someone in a new city."
meta_image: "puzzle.jpg"
